---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: Vauxite
# description will be included in the image's metadata
description: Personal Bazzite image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: module-recipes/files.yml
  - from-file: module-recipes/rpm-ostree.yml
  - from-file: module-recipes/gnome-extensions.yml
  - from-file: module-recipes/default-flatpaks.yml
  - from-file: module-recipes/icons.yml
  - type: yafti
  - from-file: module-recipes/bling.yml
  - from-file: module-recipes/fonts.yml
  - from-file: module-recipes/light-wallpaper.yml
  - from-file: module-recipes/dark-wallpaper.yml
  - from-file: module-recipes/plymouth-scripts.yml
  - from-file: module-recipes/plymouth-copy.yml
  - from-file: module-recipes/gschema-overrides.yml
  - from-file: module-recipes/dconf.yml
  - from-file: module-recipes/dconf-scripts.yml
 # - from-file: module-recipes/systemd.yml
  - type: initramfs
  - type: signing # this sets up the proper policy & signing files for signed images to work fully